name: Deploy Backend to Container in AzureVM

on:
  push:
    branches:
      - main

jobs:
  tests-backend: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'temurin'
    
    - name: Run Tharseo Tests 
      run:  mvn clean test
      
      continue-on-error: false
    
  build-backend:
    needs: 
      - tests-backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17' 
        distribution: 'temurin'

    - name: Inject secrets into application.properties
      run: |
          echo "spring.datasource.url=${{ secrets.DB_URL }}" >> src/main/resources/application.properties
          echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
          echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> src/main/resources/application.properties

    - name: Build Tharseo 
      run:  mvn clean package
      
    - name: Build Docker image
      run:  |
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
            docker build -t richardguedesrib/tharseo-app:latest .
    
    - name: Push Docker image to Docker Hub
      run: |
            docker push richardguedesrib/tharseo-app:latest

  deploy-backend:
    needs: 
      - tests-backend
      - build-backend

    runs-on: ubuntu-latest
    steps:

    - name: SSH into Azure VM and stop and remove existing Docker containers
      uses: appleboy/ssh-action@master
      with:
        host: 52.168.150.124
        username: tharseo
        password: ${{ secrets.THARSEO_BACKEND_PASS }}
        script: |
          docker stop $(docker ps -q --filter ancestor=richardguedesrib/tharseo-app) || true
          docker rm $(docker ps -aq --filter ancestor=richardguedesrib/tharseo-app) || true

    - name: SSH into Azure VM and pull Docker image
      uses: appleboy/ssh-action@master
      with:
        host: 52.168.150.124
        username: tharseo
        password: ${{ secrets.THARSEO_BACKEND_PASS }}
        script: |
          docker login && docker pull richardguedesrib/tharseo-app:latest

    - name: SSH into Azure VM and start Docker container
      uses: appleboy/ssh-action@master
      with:
        host: 52.168.150.124
        username: tharseo
        password: ${{ secrets.THARSEO_BACKEND_PASS }}
        script: |
          docker run -d -p 8080:8080 -v /home/richardguedes/tharseo/data:/app/data richardguedesrib/tharseo-app:latest

  